# name: str
#     model_name: str
#     endpoints: default to null
#         - api_base: str
#           api_key: str
#           api_version: str optional (only for azure)
#     api_type: str
#     tokenizer: str optional (to optimize token limits)
#     parallel: int
#     system_prompt: str optional (add system instruction when generating model answer)

sky-T1-32B-Preview:
    model_name: sky-T1-32B-Preview
    endpoints:
        - api_base: http://localhost:1996/v1
          api_key: a
    api_type: openai
    parallel: 8

qwen2.5-32b-instruct:
    model_name: qwen2.5-32b-instruct
    endpoints: 
        - api_base: http://localhost:1996/v1
          api_key: empty
    api_type: openai
    parallel: 8

qwq-32b-preview:
    model_name: qwq-32b-preview
    endpoints: 
        - api_base: http://localhost:1996/v1
          api_key: empty
    api_type: openai
    parallel: 8